version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: openssl-sys
    versions:
    - 0.9.60
    - 0.9.61
  - dependency-name: libc
    versions:
    - 0.2.84
    - 0.2.85
    - 0.2.86
    - 0.2.87
    - 0.2.88
    - 0.2.89
    - 0.2.90
    - 0.2.91
    - 0.2.92
    - 0.2.93
  - dependency-name: cast
    versions:
    - 0.2.4
  - dependency-name: idna
    versions:
    - 0.2.1
    - 0.2.2
  - dependency-name: js-sys
    versions:
    - 0.3.47
    - 0.3.48
    - 0.3.49
  - dependency-name: wasm-bindgen
    versions:
    - 0.2.70
    - 0.2.71
    - 0.2.72
  - dependency-name: const_fn
    versions:
    - 0.4.5
    - 0.4.6
  - dependency-name: cargo-release
    versions:
    - 0.13.10
  - dependency-name: siphasher
    versions:
    - 0.3.4
  - dependency-name: crossbeam-epoch
    versions:
    - 0.9.1
    - 0.9.2
  - dependency-name: miniz_oxide
    versions:
    - 0.4.3
  - dependency-name: unicode-normalization
    versions:
    - 0.1.16
  - dependency-name: bstr
    versions:
    - 0.2.14
  - dependency-name: libssh2-sys
    versions:
    - 0.2.20
  - dependency-name: vcpkg
    versions:
    - 0.2.11
