---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: restore
  pull: true
  image: coreyja/rust-cache:rust
  settings:
    aws_access_key_id:
      from_secret: aws_access_key_id
    aws_secret_access_key:
      from_secret: aws_secret_access_key
    cache_bucket: cache.dokku.coreyja
    cache_download: true
  depends_on:
  - clone

- name: build
  image: rust:latest
  commands:
  - rustc --version; cargo --version; rustup --version
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo build --locked --all-targets
  environment:
    CARGO_HOME: /drone/src/cargo
  depends_on:
  - restore

- name: cache
  pull: true
  image: coreyja/rust-cache:rust
  settings:
    aws_access_key_id:
      from_secret: aws_access_key_id
    aws_secret_access_key:
      from_secret: aws_secret_access_key
    cache_bucket: cache.dokku.coreyja
  failure: ignore
  depends_on:
  - build

- name: test
  image: rust:latest
  commands:
  - cargo test --locked
  environment:
    CARGO_HOME: /drone/src/cargo
  depends_on:
  - build

---
kind: signature
hmac: a3f7e163f6320dccef47d031b5be24b5cf046f10a6448f5d9718b658b3d8918c

...
