kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: restore
  image: plugins/s3-cache
  settings:
    pull: true
    root: cache.dokku.coreyja
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    restore: true
- name: build-and-test
  image: rust:latest
  environment:
    CARGO_HOME: /tmp/cargo
  commands:
  - rustc --version; cargo --version; rustup --version
  - rustup component add rustfmt
  - echo "$HOME"
  - echo "$CARGO_HOME"
- name: rebuild
  image: plugins/s3-cache
  settings:
    pull: true
    root: cache.dokku.coreyja
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    rebuild: true
    mount:
      - target/debug/.fingerprint
      - target/debug/build
      - target/debug/deps
      - /tmp/cargo/registry
    when:
      event: push
