---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: restore
  pull: true
  image: coreyja/rust-cache:rust
  settings:
    aws_access_key_id:
      from_secret: aws_access_key_id
    aws_secret_access_key:
      from_secret: aws_secret_access_key
    cache_bucket: cache.dokku.coreyja
    cache_download: true

- name: build
  image: rust:latest
  commands:
  - rustc --version; cargo --version; rustup --version
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo build --locked --all-targets
  environment:
    CARGO_HOME: /drone/src/.cargo_build

- name: cache
  pull: true
  image: coreyja/rust-cache:rust
  settings:
    aws_access_key_id:
      from_secret: aws_access_key_id
    aws_secret_access_key:
      from_secret: aws_secret_access_key
    cache_bucket: cache.dokku.coreyja

- name: test
  image: rust:latest
  commands:
  - cargo test --locked
  environment:
    CARGO_HOME: /drone/src/.cargo_build

---
kind: signature
hmac: d522bbd57591cab05f4a53165ac83ff931754eb0393bf9a2d7a36dce4d023d22

...
