kind: pipeline
name: default

platform:	
  os: linux	
  arch: amd64

steps:
- name: restore
  image: plugins/s3-cache
  settings:
    pull: true
    root: cache.dokku.coreyja
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    restore: true
- name: build
  image: rust:latest
  environment:
    CARGO_HOME: /drone/src/.cargo_build
  commands:
  - rustc --version; cargo --version; rustup --version
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo build --locked --all-targets
- name: rebuild
  image: plugins/s3-cache
  settings:
    pull: true
    root: cache.dokku.coreyja
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    rebuild: true
    mount:
      - target/debug/.fingerprint
      - target/debug/build
      - target/debug/deps
      - .cargo_build/registry
    when:
      event: push
- name: test
  image: rust:latest
  environment:
    CARGO_HOME: /drone/src/.cargo_build
  commands:
  - cargo test --locked
